In [2]:
# Import modules
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.metrics import accuracy_score

# Figures inline and set visualization style
%matplotlib inline
sns.set()

In [10]:
df_train = pd.read_csv('http://www.bccdc.ca/Health-Info-Site/Documents/BCCDC_COVID19_Regional_Summary_Data.csv')
df_train.describe()

       Cases_Reported  Cases_Reported_Smoothed
count    11102.000000             11102.000000
mean        27.003603                26.297672
std         83.803034                80.897954
min          0.000000                 0.000000
25%          0.000000                 0.000000
50%          1.000000                 1.290000
75%         14.000000                13.430000
max        992.000000               868.140000

In [11]:
# Data dictionary
# Date: date of the client's first positive lab result where available; otherwise by the date they were reported to public health
# HA: health authority assigned to the case
# HSDA: Health Service Delivery Area
# Cases_Reported: the number of cases for the health authority (HA) and health service delivery area (HSDA)
# Cases_Reported_Smoothed: Seven day moving average for reported cases

In [12]:
df_train.head()

,Date,Province,HA,HSDA,Cases_Reported,Cases_Reported_Smoothed
0,2020-01-29,BC,All,All,0,0.0
1,2020-01-29,BC,Fraser,All,0,0.0
2,2020-01-29,BC,Fraser,Fraser East,0,0.0
3,2020-01-29,BC,Fraser,Fraser North,0,0.0
4,2020-01-29,BC,Fraser,Fraser South,0,0.0